version: '3'

services:
  redis-master:
    image: redis:5.0.3-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MASTER_HOST=redis-master
    networks:
      - redis-net

  redis-slave:
    image: redis:5.0.3-alpine
    command: redis-server --slaveof redis-master 6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MASTER_HOST=redis-master
    deploy:
      replicas: 2
    networks:
      - redis-net

  redis-sentinel:
    image: bitnami/redis-sentinel
    environment:
      - REDIS_MASTER_HOST=redis-master
      - REDIS_SENTINEL_PORT=26379
    deploy:
      replicas: 3
    networks:
      - redis-net

networks:
  redis-net:
    external: true

